//@version=5
indicator(shorttitle="BB_L", title="Bollinger Bands lower band", overlay=true, timeframe="", timeframe_gaps=true)

length = input.int(20, minval=2)
maType = input.string("EMA", "Basis MA Type", options = ["SMA", "EMA"])
src = input(low, title="Source")
mult_1 = input.float(3.0, minval=0.001, maxval=50, title="StdDev")
mult_2 = input.float(5.0, minval=0.001, maxval=50, title="StdDev")

ma(source, length, _type) =>
    switch _type
        "SMA" => ta.sma(source, length)
        "EMA" => ta.ema(source, length)
        "SMMA (RMA)" => ta.rma(source, length)
        "WMA" => ta.wma(source, length)
        "VWMA" => ta.vwma(source, length)

basis = ma(src, length, maType)
lower_1 = basis - mult_1 * ta.stdev(src, length)
lower_2 = basis - mult_2 * ta.stdev(src, length)
offset = input.int(0, "Offset", minval = -500, maxval = 500, display = display.data_window)

plot(lower_1, "Lower 1", color=#0401c5, offset = offset)
plot(lower_2, "Lower 2", color=#0401c5, offset = offset)
