//@version=5
indicator(shorttitle="BB_Bands", title="Mean reversion Indicator", overlay=true, timeframe="", timeframe_gaps=true)

length = input.int(7, minval=2)
maType = input.string("EMA", "Basis MA Type", options = ["SMA", "EMA"])
entry_deviation = input.float(2.0, minval=0.001, maxval=50, title="ENTRY-StdDev")
sl_deviation = input.float(3.0, minval=0.001, maxval=50, title="SL-StdDev")

ma(source, length, _type) =>
    switch _type
        "SMA" => ta.sma(source, length)
        "EMA" => ta.ema(source, length)
        "SMMA (RMA)" => ta.rma(source, length)
        "WMA" => ta.wma(source, length)
        "VWMA" => ta.vwma(source, length)

basis_low = ma(low, length, maType)
lower_entry = basis_low - entry_deviation * ta.stdev(low, length)
lower_sl = basis_low - sl_deviation * ta.stdev(low, length)

basis_high = ma(high, length, maType)
high_entry = basis_high + entry_deviation * ta.stdev(high, length)
high_sl = basis_high + sl_deviation * ta.stdev(high, length)

offset = input.int(0, "Offset", minval = -500, maxval = 500, display = display.data_window)

plot(lower_entry, "Entry lower band", color=#0401c5, offset = offset)
plot(lower_sl, "SL lower band", color=#c50101, offset = offset)

plot(high_entry, "Entry higher band", color=#0401c5, offset = offset)
plot(high_sl, "SL higher band", color=#c50101, offset = offset)
